param:
  server-port: 8080
  db-ip: 192.168.1.13
  db-port: 3306
  db-name: webframe
  db-username: root
  db-password: 

server:
  port: ${param.server-port}
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
  tomcat:
    basedir: ./tomcat/
    accesslog:
      directory: logs
      pattern:  '%h %l %u %t %D "%r" %s %b'
      enabled: true

mybatis:
  config-locations: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mappers/*.map.xml
logging:
  path: ./logs/

spring:
  datasource:
    mainframe:
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: true
      test-while-idle: true
      time-between-eviction-runs-millis: 3600000
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://${param.db-ip}:${param.db-port}/${param.db-name}?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=round
      username: ${param.db-username}
      password: ${param.db-password}
  http:
    multipart:
      maxFileSize: 100Mb
      maxRequestSize: 100Mb
  #session:
  #  store-type: jdbc
  jdbc:
    initializer:
      enabled: true
  profiles:
    active: ${RUN_ENV}
security:
  defaultFailureUrl: /platform/login?error=true
  token_key: x-auth-account
  staticResPattern: /static/platform/**,/404*